In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_excel("../Data/Ecommerce_Dataset.csv.xls.csv")

FileNotFoundError: [Errno 2] No such file or directory: '../Data/Ecommerce_Dataset.csv.xls.csv'

In [4]:
import os

print(os.getcwd())

c:\Users\anshu\OneDrive\Desktop\project 2\SaaS-E-Commerce-Cohort-Retention-CLTV-Analysis\Notebook

In [5]:
import pandas as pd

df = pd.read_csv("../Data/raw/Ecommerce_Dataset.csv.xls.csv")

In [6]:
df.shape

(71772, 1)

In [7]:
df.columns

Index(['order_id,customer_id,transaction_date,product_category,quantity,unit_price,revenue,signup_date,acquisition_channel,country'], dtype='str')

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 71772 entries, 0 to 71771
Data columns (total 1 columns):
 #   Column                                                                                                                      Non-Null Count  Dtype
---  ------                                                                                                                      --------------  -----
 0   order_id,customer_id,transaction_date,product_category,quantity,unit_price,revenue,signup_date,acquisition_channel,country  71772 non-null  str
dtypes: str(1)
memory usage: 560.8 KB

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
df.isnull().sum()

order_id,customer_id,transaction_date,product_category,quantity,unit_price,revenue,signup_date,acquisition_channel,country    0
dtype: int64

In [11]:
df.describe()

       order_id,customer_id,transaction_date,product_category,quantity,unit_price,revenue,signup_date,acquisition_channel,country
count                                               71772
unique                                              71772
top     ORD0000001,CUST000001,2023-05-24,Fashion,4,144...
freq                                                    1

In [ ]:
##he CSV file is not using the default separator (comma) in the way Pandas expects. Sometimes this happens because:

The file is enclosed in quotes.
It was exported with a different delimiter.
There is an encoding/BOM issue.

We'll inspect it first instead of guessing.
with open("../Data/raw/Ecommerce_Dataset.csv.xls.csv", "r", encoding="utf-8") as file:
    for i in range(5):
        print(repr(file.readline()))
        
        ##repr() shows the actual characters in the file, including commas, tabs (\t), semicolons (;), quotes, etc.

'\ufeff"order_id,customer_id,transaction_date,product_category,quantity,unit_price,revenue,signup_date,acquisition_channel,country"\n'
'"ORD0000001,CUST000001,2023-05-24,Fashion,4,144.98,579.92,2023-04-13,Instagram,Canada"\n'
'"ORD0000002,CUST000002,2024-03-18,Beauty,3,28.21,84.63,2024-03-11,Email,USA"\n'
'"ORD0000003,CUST000002,2024-04-09,Beauty,4,24.68,98.72,2024-03-11,Email,USA"\n'
'"ORD0000004,CUST000002,2024-05-05,Fashion,2,35.77,71.54,2024-03-11,Email,USA"\n'

In [13]:
df = pd.read_csv("../Data/raw/Ecommerce_Dataset.csv.xls.csv", encoding="utf-8-sig")

In [14]:
df.head()

  order_id,customer_id,transaction_date,product_category,quantity,unit_price,revenue,signup_date,acquisition_channel,country
0  ORD0000001,CUST000001,2023-05-24,Fashion,4,144...
1  ORD0000002,CUST000002,2024-03-18,Beauty,3,28.2...
2  ORD0000003,CUST000002,2024-04-09,Beauty,4,24.6...
3  ORD0000004,CUST000002,2024-05-05,Fashion,2,35....
4  ORD0000005,CUST000002,2024-06-20,Sports,2,19.6...

In [ ]:
##Notice two things:
#The entire header is inside quotes "...".
#Every row is also inside quotes.
#So Pandas is treating each line as one string instead of splitting it into columns.

df = pd.read_csv(
    "../Data/raw/Ecommerce_Dataset.csv.xls.csv",
    header=None,
    encoding="utf-8-sig"
)

In [ ]:
##Now assign the correct column names:
df = df[0].str.replace('"', '', regex=False).str.split(",", expand=True)

In [ ]:
##Now assign the correct column names:
df.columns = [
    "order_id",
    "customer_id",
    "transaction_date",
    "product_category",
    "quantity",
    "unit_price",
    "revenue",
    "signup_date",
    "acquisition_channel",
    "country"
]

In [ ]:
##Since the original header is now the first row of data, remove it:
df = df.iloc[1:].reset_index(drop=True)

In [21]:
df.head()

,order_id,customer_id,transaction_date,product_category,quantity,unit_price,revenue,signup_date,acquisition_channel,country
0,ORD0000001,CUST000001,2023-05-24,Fashion,4,144.98,579.92,2023-04-13,Instagram,Canada
1,ORD0000002,CUST000002,2024-03-18,Beauty,3,28.21,84.63,2024-03-11,Email,USA
2,ORD0000003,CUST000002,2024-04-09,Beauty,4,24.68,98.72,2024-03-11,Email,USA
3,ORD0000004,CUST000002,2024-05-05,Fashion,2,35.77,71.54,2024-03-11,Email,USA
4,ORD0000005,CUST000002,2024-06-20,Sports,2,19.67,39.34,2024-03-11,Email,USA

In [ ]:
##Check the shape
df.shape

(71772, 10)

In [ ]:
##Week 1 – Part 2: Data Understanding (EDA)
#Before cleaning data, we must understand it.
#Step 1: Check the First 10 Records

df.head(10)

##Why?
#This helps us verify:

#Values are in the correct columns.
#Dates look correct.
#No obvious formatting issues.

,order_id,customer_id,transaction_date,product_category,quantity,unit_price,revenue,signup_date,acquisition_channel,country
0,ORD0000001,CUST000001,2023-05-24,Fashion,4,144.98,579.92,2023-04-13,Instagram,Canada
1,ORD0000002,CUST000002,2024-03-18,Beauty,3,28.21,84.63,2024-03-11,Email,USA
2,ORD0000003,CUST000002,2024-04-09,Beauty,4,24.68,98.72,2024-03-11,Email,USA
3,ORD0000004,CUST000002,2024-05-05,Fashion,2,35.77,71.54,2024-03-11,Email,USA
4,ORD0000005,CUST000002,2024-06-20,Sports,2,19.67,39.34,2024-03-11,Email,USA
5,ORD0000006,CUST000002,2024-07-03,Sports,2,249.32,498.64,2024-03-11,Email,USA
6,ORD0000007,CUST000002,2024-08-27,Fashion,2,102.71,205.42,2024-03-11,Email,USA
7,ORD0000008,CUST000002,2024-10-12,Beauty,3,157.96,473.88,2024-03-11,Email,USA
8,ORD0000009,CUST000003,2023-10-21,Sports,3,119.92,359.76,2023-09-28,Facebook Ads,France
9,ORD0000010,CUST000004,2023-04-25,Electronics,3,14.85,44.55,2023-04-17,Facebook Ads,Germany

In [ ]:
##Step 2: Check the Shape

df.shape

#Explanation
#71,772 rows = total transactions.
#10 columns = attributes about each transaction.

(71772, 10)

In [ ]:
##Display Column Names
df.columns

##Why?

##We need to know the exact column names because we'll reference them throughout the project.

Index(['order_id', 'customer_id', 'transaction_date', 'product_category',
       'quantity', 'unit_price', 'revenue', 'signup_date',
       'acquisition_channel', 'country'],
      dtype='str')

In [ ]:
##Check Data Types
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 71772 entries, 0 to 71771
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   order_id             71772 non-null  str
 1   customer_id          71772 non-null  str
 2   transaction_date     71772 non-null  str
 3   product_category     71772 non-null  str
 4   quantity             71772 non-null  str
 5   unit_price           71772 non-null  str
 6   revenue              71772 non-null  str
 7   signup_date          71772 non-null  str
 8   acquisition_channel  71772 non-null  str
 9   country              71772 non-null  str
dtypes: str(10)
memory usage: 5.5 MB

In [ ]:
##Convert Date Columns
df["transaction_date"] = pd.to_datetime(df["transaction_date"])
df["signup_date"] = pd.to_datetime(df["signup_date"])

##After conversion, Python understands it as a date, allowing us to calculate:

Month
Year
Day
Cohort Month
Retention Period

In [ ]:
##Convert Quantity
df["quantity"] = df["quantity"].astype(int)

##Why?

Quantity is a whole number.

Example:

4 Products
2 Products
10 Products

Python should store these as integers.

In [ ]:
##Convert Unit Price
df["unit_price"] = df["unit_price"].astype(float)

##Why?

Prices have decimal values.

Example:

144.98
79.50
22.35

These should be floating-point numbers.

In [ ]:
##Convert Revenue
df["revenue"] = df["revenue"].astype(float)

#Revenue also contains decimal values.

In [31]:
#Verify the Changes

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 71772 entries, 0 to 71771
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   order_id             71772 non-null  str
 1   customer_id          71772 non-null  str
 2   transaction_date     71772 non-null  datetime64[us]
 3   product_category     71772 non-null  str
 4   quantity             71772 non-null  int64
 5   unit_price           71772 non-null  float64
 6   revenue              71772 non-null  float64
 7   signup_date          71772 non-null  datetime64[us]
 8   acquisition_channel  71772 non-null  str
 9   country              71772 non-null  str
dtypes: datetime64[us](2), float64(2), int64(1), str(5)
memory usage: 5.5 MB

In [32]:
df["transaction_date"] = pd.to_datetime(df["transaction_date"])
df["signup_date"] = pd.to_datetime(df["signup_date"])

df["quantity"] = df["quantity"].astype(int)

df["unit_price"] = df["unit_price"].astype(float)

df["revenue"] = df["revenue"].astype(float)

In [33]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 71772 entries, 0 to 71771
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   order_id             71772 non-null  str
 1   customer_id          71772 non-null  str
 2   transaction_date     71772 non-null  datetime64[us]
 3   product_category     71772 non-null  str
 4   quantity             71772 non-null  int64
 5   unit_price           71772 non-null  float64
 6   revenue              71772 non-null  float64
 7   signup_date          71772 non-null  datetime64[us]
 8   acquisition_channel  71772 non-null  str
 9   country              71772 non-null  str
dtypes: datetime64[us](2), float64(2), int64(1), str(5)
memory usage: 5.5 MB

In [ ]:
##Check Missing Values
df.isnull().sum()

#Why?

Missing values can affect:

Cohort analysis
Retention calculations
CLTV

We'll remove or fill them if needed.

order_id               0
customer_id            0
transaction_date       0
product_category       0
quantity               0
unit_price             0
revenue                0
signup_date            0
acquisition_channel    0
country                0
dtype: int64

In [ ]:
#Check Duplicate Rows
df.duplicated().sum()

##If duplicates exist:
df.drop_duplicates(inplace=True)

##Why?

Duplicate transactions would inflate revenue and retention metrics.

In [ ]:
##Summary Statistics
df.describe()

##Focus on:

Quantity
Unit Price
Revenue

We'll look for impossible values such as:

Negative quantity
Zero price
Extremely large revenue

,transaction_date,quantity,unit_price,revenue,signup_date
count,71772,71772.000000,71772.000000,71772.000000,71772
mean,2024-03-01 16:17:04.444072,2.500543,129.780982,324.114706,2023-11-04 04:09:39.033606
min,2023-01-09 00:00:00,1.000000,10.000000,10.000000,2023-01-01 00:00:00
25%,2023-10-04 00:00:00,2.000000,69.357500,134.310000,2023-05-30 00:00:00
50%,2024-03-12 00:00:00,2.000000,129.580000,248.285000,2023-10-25 00:00:00
75%,2024-08-08 00:00:00,4.000000,189.610000,469.920000,2024-04-01 00:00:00
max,2024-12-31 00:00:00,4.000000,249.990000,999.960000,2024-12-20 00:00:00
std,NaN,1.118278,69.358783,238.430900,NaN

In [39]:
##After that, we'll create the most important column of the project:
## Create Cohort Month

##A cohort is a group of customers who first purchased in the same month.

##We'll create it with:

df["cohort_month"] = (
    df.groupby("customer_id")["transaction_date"]
      .transform("min")
      .dt.to_period("M")
)

In [ ]:
##Understanding the code
df.groupby("customer_id")

In [41]:
##Groups all transactions by customer.
["transaction_date"].transform("min")

AttributeError: 'list' object has no attribute 'transform'

In [42]:
#Finds the earliest purchase date for each customer.

.dt.to_period("M")

SyntaxError: invalid syntax (1671293528.py, line 3)

In [43]:
df["cohort_month"] = df.groupby("customer_id")["transaction_date"].transform("min").dt.to_period("M")

In [ ]:
#Verify the New Column
df[["customer_id", "transaction_date", "cohort_month"]].head(10)

#Notice how the same customer keeps the same cohort_month, even on later purchases. That's exactly what we need for Week 2's retention analysis.

  customer_id transaction_date cohort_month
0  CUST000001       2023-05-24      2023-05
1  CUST000002       2024-03-18      2024-03
2  CUST000002       2024-04-09      2024-03
3  CUST000002       2024-05-05      2024-03
4  CUST000002       2024-06-20      2024-03
5  CUST000002       2024-07-03      2024-03
6  CUST000002       2024-08-27      2024-03
7  CUST000002       2024-10-12      2024-03
8  CUST000003       2023-10-21      2023-10
9  CUST000004       2023-04-25      2023-04

In [45]:
#Save the Cleaned Dataset
#Createing  the cleaned dataset for future weeks:

df.to_csv("../Data/cleaned/cleaned_transactions.csv", index=False)